apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  type: LoadBalancer # This creates an AWS Load Balancer to expose your service
  ports:
  - port: 80
    targetPort: 5000
